### ISSUE TITLE
incorrect pan handling after device rotation

### ISSUE THREAD

**Issue by anton-filimonov** [Kofktu/KUIKeyboard#2]
Steps to reproduce:
- keyboardDismissMode = .interactive
- Landscape mode
- show keyboard
- hide keyboard
- portrait mode
- scroll content

Result: got message like keyboard is visible
Expected result: no messages till keyboard appear

**Comment by anton-filimonov** [comment]
[related pull request](https://github.com/Kofktu/KUIKeyboard/pull/3)

**Comment by Kofktu** [comment]
Merged PR #3
